import type { RiskItem, RoadmapPhase } from './types';

export const RISK_REGISTRY: RiskItem[] = [
  {
    id: 'R-01',
    category: 'organizational',
    title: 'Staff Resistance to RFID/Digital Systems',
    description: 'Ward pharmacists and store staff may resist transitioning from manual processes to RFID-based tracking and digital reorder systems, citing workload concerns and unfamiliarity.',
    likelihood: 'High',
    impact: 'High',
    riskScore: 9,
    mitigation: 'Phased rollout with champion pharmacists in 2-3 pilot wards. Provide 40-hour training program. Demonstrate time savings with real data within 60 days. Secure union/staff association buy-in before deployment.',
    owner: 'Chief Pharmacist + HR Director',
    timeline: 'Phase 1-2 (Months 1-6)',
  },
  {
    id: 'R-02',
    category: 'regulatory',
    title: 'PPRA Rule Conflict with Pre-Approved Frameworks',
    description: 'The proposed emergency blanket contract mechanism may face legal challenge under PPRA Rules 2004, specifically Rule 12 (methods of procurement) and Rule 42 (emergency procurement).',
    likelihood: 'Medium',
    impact: 'High',
    riskScore: 8,
    mitigation: 'Engage PPRA counsel to draft compliant framework. Use Rule 42 "emergency" provisions with pre-documented justification template. Obtain AG office opinion before implementation. Limit individual order value to Rs 1.9M (below committee threshold).',
    owner: 'Hospital Procurement Director + Legal Advisor',
    timeline: 'Phase 1 (Months 1-3)',
  },
  {
    id: 'R-03',
    category: 'financial',
    title: 'Budget Allocation for CAPEX Investment',
    description: 'The Rs 18.5M total implementation cost requires dedicated funding that may not be available in the current development budget of a public sector hospital.',
    likelihood: 'High',
    impact: 'Medium',
    riskScore: 7,
    mitigation: 'Present ROI analysis (payback < 4 months) to Finance Committee. Propose phased investment aligned with quarterly budget tranches. Apply for Punjab Health Department Innovation Fund. Consider PPP model for RFID infrastructure.',
    owner: 'Medical Superintendent + Finance Director',
    timeline: 'Phase 0 (Pre-implementation)',
  },
  {
    id: 'R-04',
    category: 'technical',
    title: 'ERP Integration Complexity',
    description: 'Existing hospital ERP (if any) may not support consumption-based reorder APIs. Legacy systems may lack real-time stock visibility required for automated triggers.',
    likelihood: 'Medium',
    impact: 'Medium',
    riskScore: 6,
    mitigation: 'Conduct technical assessment of current IT infrastructure in Phase 0. Deploy standalone module if ERP integration is not feasible. Use barcode scanning as fallback for RFID. Ensure offline-capable architecture for power/network disruptions.',
    owner: 'IT Director + Vendor Implementation Team',
    timeline: 'Phase 1-2 (Months 1-9)',
  },
  {
    id: 'R-05',
    category: 'organizational',
    title: 'Finance Department Non-Cooperation on Advance Requisition',
    description: 'Provincial Finance Department may not accept advance budget requisition mechanism, as it requires process change at the government level beyond hospital authority.',
    likelihood: 'High',
    impact: 'Medium',
    riskScore: 7,
    mitigation: 'Present patient harm data and financial waste analysis to Additional Secretary Health. Propose pilot with one fiscal year trial. Benchmark against military hospital procurement (AMC already uses advance requisition). Engage Punjab Assembly Standing Committee on Health.',
    owner: 'Hospital MS + Secretary Health Punjab',
    timeline: 'Phase 2-3 (Months 6-15)',
  },
  {
    id: 'R-06',
    category: 'technical',
    title: 'RFID Tag Reliability in Hospital Environment',
    description: 'Pharmaceutical storage areas may have environmental conditions (humidity, temperature, electromagnetic interference from MRI/CT) that degrade RFID tag performance.',
    likelihood: 'Medium',
    impact: 'Low',
    riskScore: 4,
    mitigation: 'Use UHF RFID tags rated for pharmaceutical environments. Conduct site survey with vendor before deployment. Implement dual tracking (RFID + barcode) for critical items. Add environmental monitoring to storage areas.',
    owner: 'IT Director + Facilities Manager',
    timeline: 'Phase 2 (Months 4-9)',
  },
  {
    id: 'R-07',
    category: 'financial',
    title: 'Vendor Lock-in for RFID Hardware',
    description: 'Proprietary RFID systems from a single vendor may create dependency, inflating long-term maintenance costs and limiting future technology upgrades.',
    likelihood: 'Medium',
    impact: 'Medium',
    riskScore: 5,
    mitigation: 'Mandate ISO 18000-6C (EPC Gen2) compliance in RFP. Use multi-vendor-compatible readers. Ensure data export in open formats. Include vendor transition clause in contract.',
    owner: 'Procurement Director + IT Director',
    timeline: 'Phase 1 (Months 1-3)',
  },
  {
    id: 'R-08',
    category: 'regulatory',
    title: 'Drug Regulatory Authority Reporting Changes',
    description: 'DRAP may introduce new batch tracking or serialisation requirements that conflict with the implemented system architecture.',
    likelihood: 'Low',
    impact: 'Medium',
    riskScore: 3,
    mitigation: 'Design system with modular serialisation support from day one. Monitor DRAP regulatory updates quarterly. Maintain buffer capacity for additional data fields in batch records.',
    owner: 'Chief Pharmacist + QA Director',
    timeline: 'Ongoing',
  },
  {
    id: 'R-09',
    category: 'organizational',
    title: 'Knowledge Transfer During Political Transitions',
    description: 'Hospital leadership changes during provincial government transitions may deprioritise or reverse implemented changes.',
    likelihood: 'High',
    impact: 'High',
    riskScore: 9,
    mitigation: 'Embed system into formal hospital SOPs (cannot be reversed by individual). Get Punjab Health Policy Board endorsement. Publish results in peer-reviewed journal for institutional credibility. Train multiple system administrators.',
    owner: 'Medical Superintendent + MS Office',
    timeline: 'Phase 3-4 (Months 9-18)',
  },
  {
    id: 'R-10',
    category: 'technical',
    title: 'Data Accuracy During Manual Data Entry Phase',
    description: 'Before full RFID deployment, consumption data entry will be manual, potentially introducing errors that undermine consumption-based reorder accuracy.',
    likelihood: 'High',
    impact: 'Medium',
    riskScore: 7,
    mitigation: 'Implement daily data validation checks. Use barcode scanning (lower cost than RFID) as interim solution. Cross-validate consumption data against dispensing records. Set accuracy KPIs with ward-level accountability.',
    owner: 'Chief Pharmacist + Ward Supervisors',
    timeline: 'Phase 1-2 (Months 1-6)',
  },
  {
    id: 'R-11',
    category: 'financial',
    title: 'Savings Reabsorption by Government',
    description: 'Demonstrated savings from reduced waste may lead Finance Department to cut the hospital budget proportionally, eliminating the financial benefit.',
    likelihood: 'Medium',
    impact: 'High',
    riskScore: 7,
    mitigation: 'Frame savings as "service expansion" not "cost reduction". Use freed budget for previously unfunded clinical needs (new equipment, additional drug categories). Ensure savings are documented as improved patient outcomes, not fiscal surplus.',
    owner: 'Finance Director + Medical Superintendent',
    timeline: 'Phase 3-4 (Months 12-18)',
  },
  {
    id: 'R-12',
    category: 'technical',
    title: 'Power and Network Infrastructure Gaps',
    description: 'Consistent power supply and network connectivity required for RFID readers and digital systems may not be available in all pharmacy/store locations.',
    likelihood: 'Medium',
    impact: 'Medium',
    riskScore: 5,
    mitigation: 'Deploy UPS at each RFID reader point (cost included in CAPEX). Use offline-capable mobile devices for data entry. Implement data sync queues for intermittent connectivity. Include infrastructure assessment in Phase 0.',
    owner: 'IT Director + Facilities',
    timeline: 'Phase 1 (Months 1-3)',
  },
];

export const ROADMAP_PHASES: RoadmapPhase[] = [
  {
    id: 'P0',
    phase: 0,
    name: 'Foundation & Assessment',
    duration: '3 months',
    startMonth: 0,
    endMonth: 3,
    description: 'Comprehensive assessment of current infrastructure, stakeholder mapping, regulatory review, and vendor evaluation. Establish governance structure and secure initial funding.',
    activities: [
      'Conduct IT infrastructure and network assessment across all pharmacy/store locations',
      'Map current procurement workflows and identify bottlenecks',
      'Engage PPRA legal counsel for emergency framework compliance review',
      'Issue RFP for RFID hardware and ERP integration vendors',
      'Establish Project Steering Committee (MS, Chief Pharmacist, Finance, IT)',
      'Develop detailed implementation SOP and change management plan',
      'Baseline data collection: 30-day manual consumption audit across 40 critical SKUs',
      'Present business case and ROI analysis to Hospital Management Board',
    ],
    deliverables: [
      'Infrastructure Assessment Report',
      'Vendor Evaluation Matrix',
      'PPRA Legal Opinion',
      'Project Charter & Governance Structure',
      'Baseline Data Report',
      'Approved Budget Allocation',
    ],
    investmentRs: 1_200_000,
    dependencies: [],
    risks: ['R-03', 'R-02'],
    kpis: [
      { metric: 'Stakeholder sign-offs', target: '100% of committee members' },
      { metric: 'Baseline audit completion', target: '40 critical SKUs audited' },
      { metric: 'Vendor shortlisting', target: '≥3 qualified vendors' },
    ],
  },
  {
    id: 'P1',
    phase: 1,
    name: 'Quick Wins & Policy Changes',
    duration: '3 months',
    startMonth: 3,
    endMonth: 6,
    description: 'Implement zero/low-cost interventions: advance budget requisition process, emergency procurement framework, and manual consumption tracking pilot in 3 wards.',
    activities: [
      'Prepare and submit advance budget requisition to Finance Department',
      'Draft and execute emergency blanket procurement contracts for top 20 critical SKUs',
      'Deploy manual consumption logging in 3 pilot wards (Emergency, General Surgery, Medicine)',
      'Train 15 ward pharmacists on consumption-based forecasting methodology',
      'Establish daily stock verification protocol for critical items',
      'Begin cold storage facility upgrade design and tender',
      'Implement WhatsApp-based stockout alert system (interim)',
      'Conduct first monthly review with Steering Committee',
    ],
    deliverables: [
      'Advance Budget Requisition submitted',
      'Emergency Blanket Contracts (top 20 SKUs)',
      'Ward-level Consumption Tracking Sheets',
      'Pharmacist Training Completion Certificates',
      'Cold Storage Upgrade Tender Document',
    ],
    investmentRs: 1_800_000,
    dependencies: ['P0'],
    risks: ['R-05', 'R-01', 'R-10'],
    kpis: [
      { metric: 'Advance requisition acceptance', target: 'Submitted and acknowledged' },
      { metric: 'Emergency contracts signed', target: '≥15 of 20 critical SKUs' },
      { metric: 'Pilot ward data capture rate', target: '≥85% of daily consumption logged' },
    ],
  },
  {
    id: 'P2',
    phase: 2,
    name: 'Technology Deployment',
    duration: '6 months',
    startMonth: 6,
    endMonth: 12,
    description: 'Deploy RFID infrastructure, implement ERP consumption module, roll out consumption-based reorder system hospital-wide, and complete pre-positioning storage upgrade.',
    activities: [
      'Install RFID readers and tags in Central Pharmacy and 5 satellite stores',
      'Deploy ERP consumption tracking module (or standalone system)',
      'Migrate from manual to digital consumption tracking across all wards',
      'Implement automated reorder triggers based on 14-day moving average',
      'Complete cold storage facility upgrade for pre-positioning inventory',
      'Execute first pre-positioning cycle (April-June) for upcoming FY',
      'Train remaining pharmacists and store staff (40 personnel)',
      'Deploy real-time dashboard for stock visibility',
      'Conduct FIFO compliance audit in all storage locations',
      'Integrate emergency procurement alerts with digital system',
    ],
    deliverables: [
      'RFID System Operational (Central Pharmacy + 5 stores)',
      'Consumption-Based Reorder Module Live',
      'Cold Storage Facility Operational',
      'Real-time Stock Dashboard',
      'FIFO Compliance Report',
      'System User Manual & Training Materials',
    ],
    investmentRs: 12_000_000,
    dependencies: ['P1'],
    risks: ['R-04', 'R-06', 'R-07', 'R-12'],
    kpis: [
      { metric: 'RFID read accuracy', target: '≥98% tag read rate' },
      { metric: 'Automated reorder trigger coverage', target: '≥80% of 200 SKUs' },
      { metric: 'Forecast MAPE reduction', target: '≤15% (from baseline ~40%)' },
      { metric: 'FIFO compliance rate', target: '≥90% of picks' },
    ],
  },
  {
    id: 'P3',
    phase: 3,
    name: 'Optimisation & Scaling',
    duration: '6 months',
    startMonth: 12,
    endMonth: 18,
    description: 'Full system optimisation using real data. Extend to remaining storage locations. Implement predictive analytics and seasonal demand forecasting. Institutionalise processes.',
    activities: [
      'Extend RFID to remaining satellite pharmacies and surgical stores',
      'Implement seasonal demand prediction model using 12-month historical data',
      'Fine-tune reorder parameters (safety stock, lead time buffers) monthly',
      'Develop automated PPRA compliance documentation module',
      'Establish quarterly supplier performance review mechanism',
      'Publish first annual Supply Chain Performance Report',
      'Embed SOPs into hospital accreditation documentation',
      'Present results at Punjab Health Systems Conference',
      'Develop KPI dashboards for MS, Finance, and Pharmacy leadership',
      'Assess expansion to outpatient pharmacy and emergency drug cabinet',
    ],
    deliverables: [
      'Full Hospital RFID Coverage',
      'Seasonal Demand Prediction Model',
      'Automated PPRA Documentation Module',
      'Annual Supply Chain Performance Report',
      'Updated Hospital SOPs',
      'Conference Presentation & Publication Draft',
    ],
    investmentRs: 3_500_000,
    dependencies: ['P2'],
    risks: ['R-09', 'R-11', 'R-08'],
    kpis: [
      { metric: 'Critical stockout rate', target: '≤3% (from baseline ~14%)' },
      { metric: 'Annual expiry waste', target: '≤4% of budget (from ~13.5%)' },
      { metric: 'Patient OOP events reduction', target: '≥70% reduction' },
      { metric: 'Forecast MAPE', target: '≤11%' },
      { metric: 'Emergency procurement premium', target: '≤12% (from ~30%)' },
    ],
  },
];
